spring.application.name=hungry-pang-project

server.port=8080

# DB ??
spring.datasource.url=jdbc:mysql://localhost:3306/hungrypang?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=12345678
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# data.sql ?? ??
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.main.allow-bean-definition-overriding=true

jwt.secret.key=thisIsATemporarySecretKeyForDevelopmentOnly1234567890
portone.api.key=store-2352c594-38f8-47ee-9e9a-b2cd99a1100b
portone.api.secret=PmPcFdlWBUVTtfkq4YtC6WOfM6NWAFEl9oxxqtnoN07XeAhF6nNzBtI3HW4iHZ77glXMRu3tjUlRdE0M